<?php
namespace Tests\Feature\Services;

use Log;
use Tests\TestCase;
use LINE\LINEBot;
use App\Services\LineBotService;


class LineBotServiceTest extends TestCase
{
    /** @var  LineBotService */
    private $lineBotService;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->lineBotService = app(LineBotService::class);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testPushMessage()
    {

        $response = $this->lineBotService->pushMessage('Test from laravel.');
        Log::info($response->getRawBody());
        $this->assertEquals(200, $response->getHTTPStatus());
    }


}